name: "Swift Build & Test"

on:
  push:
    branches: "main"
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: macos-latest    # Utilisation de macOS au lieu d'Ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: xcodebuild build
      - name: Run tests
        run: xcodebuild test
