name: "Swift Build & Test"

on:
  push:
    branches: "main"
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: macos-14  # Pour obtenir la dernière version de macOS
    steps:
      - uses: actions/checkout@v4
      
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
        
      - name: Build
        run: xcodebuild build -scheme testGitCiCd -sdk iphonesimulator -configuration Debug
        
      - name: Test
        run: xcodebuild test -scheme testGitCiCd -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' -configuration Debug
