name: "Swift Build & Test"

on:
  push:
    branches: 
      - 'release/**'  # Uniquement sur les branches de release
  pull_request:
    branches: 
      - 'release/**'

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          project_path=$(find . -name "*.xcodeproj" -type d)
          xcodebuild build -project "$project_path" -scheme testGitCiCD -sdk iphonesimulator -configuration Debug
        
      - name: Test
        run: |
          project_path=$(find . -name "*.xcodeproj" -type d)
          xcodebuild test -project "$project_path" -scheme testGitCiCD -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' -configuration Debug
