name: "Swift Build & Test"

on:
  push:
   branches:
     - main
     - 'testBranche'
     - 'origin/**'
     - 'origin/*'
     - 'hotfix/**'
     - '**'
  
  pull_request:
    branches: 
      - main
      - '**'

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          project_path=$(find . -name "*.xcodeproj" -type d)
          xcodebuild build -project "$project_path" -scheme testGitCiCD -sdk iphonesimulator -configuration Debug
        
