name: "Swift Build & Test"

on:
  push:
    branches: "main"
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and Test
        run: |
          xcodebuild build -scheme testGitCiCd -sdk iphonesimulator
          xcodebuild test -scheme testGitCiCd -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
