name: "Swift Build & Test"

on:
  push:
    branches: "main"
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show Xcode version
        run: xcodebuild -version
      
      - name: Show build settings
        run: xcodebuild -scheme testGitCiCD -showBuildSettings
        
      - name: Show available schemes
        run: xcodebuild -list
        
      - name: Build
        run: xcodebuild build -scheme testGitCiCD -sdk iphonesimulator -configuration Debug | xcpretty && exit ${PIPESTATUS[0]}
        
      - name: Test
        run: xcodebuild test -scheme testGitCiCD -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' -configuration Debug | xcpretty && exit ${PIPESTATUS[0]}
