
name: "Swift Build & Test"

on:
  push:
    branches: "main"
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show current directory
        run: pwd && ls -la
        
      - name: Show Xcode projects
        run: find . -name "*.xcodeproj" -type d
        
      - name: Show project content
        run: |
          cd *.xcodeproj || exit 1
          ls -la
          cd xcshareddata/xcschemes || exit 1
          ls -la
        
      - name: List available schemes
        run: xcodebuild -list
        
      - name: Build
        run: |
          project_name=$(find . -name "*.xcodeproj" -type d -maxdepth 1 | head -n 1)
          xcodebuild build -project "$project_name" -scheme testGitCiCd -sdk iphonesimulator -configuration Debug
